### Get All Users
GET http://localhost:3000/user

###
# GET http://dearsurvy.herokuapp.com/user/4

###
POST http://localhost:3000/user/signup
Content-Type: "application/json"

{
	"username": "workout2@gmail.com",
    "password": "workout"
}

### getById
GET http://localhost:3000/user/4
